### ISSUE TITLE
[BUG] Link (pipe) between Lookup Query and Subgraph gone

### ISSUE THREAD

**Issue by SabineVanEs** [marklogic-community/pipes#316] opened 2020-10-12 08:11 UTC
**Describe the bug**
In Pipes I'm currently using a subgraph for mapping. Each time I save the graph and open it later on the connection between the last Lookup and the subgraph is gone. This does not only happens with me but with my collagues. 

**To Reproduce**

1. On the Main graph create a Lookup Query and link the output to a subgraph. 
2. Save the graph
3. Close and reopen the graph
4. See attachment for result

**Expected behavior**
I would expect the link between the Lookup Query and the subgraph to keep existing after saving and reopening the graph. 

**Screenshots**
![Pipes1](https://user-images.githubusercontent.com/72729991/95721271-a214a880-0c72-11eb-9aef-7d5a74047654.PNG)

![Pipes2](https://user-images.githubusercontent.com/72729991/95721447-e43dea00-0c72-11eb-9cba-296a882d1bbc.PNG)

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: Chrome
 - Version: Version 86.0.4240.75 (Official build) (64-bits)

**Comment by josvanroosmalen** [comment] 2020-10-12 08:38
I will send you an email.

**Comment by josvanroosmalen** [comment] 2020-10-13 04:22
I can reproduce this issue. I will look into this.

**Comment by josvanroosmalen** [comment] 2020-10-13 06:28
Root cause found. Fix in progress.

**Comment by josvanroosmalen** [comment] 2020-10-13 07:09
Fixed. Shipping this bug. Fixed in release 1.4

**Closed as completed by josvanroosmalen** 2020-10-13 07:09 UTC

**Comment by SabineVanEs** [comment] 2020-10-14 16:26
The release is installed and working fine. Thanks!
