### ISSUE TITLE
Search block should have an option to run unfiltered

### ISSUE THREAD

**Issue by josvanroosmalen** [marklogic-community/pipes#164] opened 2020-04-02 13:58 UTC
Search block should have an option to run unfiltered. 

Will do this for performance reasons for the POC now in the poc1 branch.

**Comment by sashamitrovich** [comment] 2020-04-06 07:25
This is a duplicate of #149. Can you confirm, @josvanroosmalen ?

**Comment by sashamitrovich** [comment] 2020-04-14 11:23
Closing, duplicate.

**Closed as completed by sashamitrovich** 2020-04-14 11:23 UTC
Labels: duplicate
